name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  push_to_registry_of_student:
    name: Push Docker image to Docker Hub and Deploy
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hamxaakhtar/django:latest
          labels: |
            org.opencontainers.image.description=This repo is for Django todo app deployment as a Devops engineer via Jenkins
            org.opencontainers.image.url=https://github.com/Hamxaakhtar/django-todo-cicd
            org.opencontainers.image.version=1.0.0  # Replace with your version
      
      - name: Deploy to EC2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_PUBLIC_IP }}
          USER_NAME: ${{ secrets.USER_NAME }}
          
        run: |
          echo "$PRIVATE_KEY " > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 'cd django-todo-cicd/ && docker-compose up --build -d'
