name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_to_registry_of_student:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hamxaakhtar/django:latest
          labels: |
            org.opencontainers.image.description=This repo is for Django todo app deployment as a Devops engineer via Jenkins
            org.opencontainers.image.url=https://github.com/Hamxaakhtar/django-todo-cicd
            org.opencontainers.image.version=1.0.0  # Replace with your version

      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{ secrets.HOST_DNS }}
            USER_NAME: ${{ secrets.USERNAME }}
      
        run: |
          echo "$EC2_SSH_KEY " > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Now we have got the access of EC2 and we will start the deploy .
              docker-compose pull && docker-compose up -d '

          
